# Generated by Django 3.1.5 on 2021-02-12 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='review',
        ),
    ]
