# Generated by Django 3.1.5 on 2021-02-13 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_comment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(default=None, max_length=80),
            preserve_default=False,
        ),
    ]
